import os
import sys
import subprocess
import argparse

def main():
    parser = argparse.ArgumentParser(description="Run SFS and Bootstrap comparison pipeline (Computation + Visualisation + Patient Plots) on Synthetic Benchmark")
    parser.add_argument("--sample_files", nargs="+", default=["tests/data/Supplementary_data_Diaz-Gay_et_al_2023_Benchmark/SBS/Samples.txt"], help="Path to sample files")
    parser.add_argument("--output_dirs", nargs="+", default=["synthetic2700_all"], help="Output directories corresponding to sample files")
    parser.add_argument("--sig_file", default="tests/data/Supplementary_data_Diaz-Gay_et_al_2023_Benchmark/SBS/COSMIC_v3.3_SBS_GRCh37.txt", help="Path to signatures file")
    parser.add_argument("--truth_file", default="tests/data/Supplementary_data_Diaz-Gay_et_al_2023_Benchmark/SBS/ground.truth.syn.exposures.csv", help="Path to ground truth exposures")
    parser.add_argument("--hybrid", action="store_true", help="Run hybrid bootstrap SFS")
    
    args = parser.parse_args()
    
    if len(args.sample_files) != len(args.output_dirs):
        print("Error: The number of sample files must match the number of output directories.")
        sys.exit(1)
        
    for i, (sample_file, output_dir) in enumerate(zip(args.sample_files, args.output_dirs)):
        print(f"\n=======================================================")
        print(f"Running synthetic pipeline for sample: {sample_file}")
        print(f"Output directory: {output_dir}")
        print(f"=======================================================\n")
        
        # 1. Computation step
        print(f"=== Starting Computation ===")
        compute_script = os.path.join(os.path.dirname(__file__), "compute_comparison_synthetic.py")
        
        compute_cmd = [
            sys.executable, compute_script,
            "--sample_file", sample_file,
            "--sig_file", args.sig_file,
            "--truth_file", args.truth_file,
            "--output_dir", output_dir,
            "--hybrid", "1" if args.hybrid else "0"
        ]
        
        result_compute = subprocess.run(compute_cmd)
        if result_compute.returncode != 0:
            print(f"Error: Computation script failed for {sample_file}.")
            sys.exit(result_compute.returncode)
            
        # 2. Visualisation step
        print(f"\n=== Starting Visualisation ===")
        visualise_script = os.path.join(os.path.dirname(__file__), "visualise_comparison_synthetic.py")
        
        vis_cmd = [
            sys.executable, visualise_script,
            "--output_dir", output_dir
        ]
        
        result_vis = subprocess.run(vis_cmd)
        if result_vis.returncode != 0:
            print(f"Error: Visualisation script failed for {sample_file}.")
            sys.exit(result_vis.returncode)

        # 3. Patient Plots step
        print(f"\n=== Starting Patient Plots ===")
        plots_script = os.path.join(os.path.dirname(__file__), "generate_synthetic_patient_plots.py")
        
        plots_cmd = [
            sys.executable, plots_script,
            "--sample_file", sample_file,
            "--output_dir", output_dir
        ]
        
        if i == 0:
            plots_cmd.extend(["--patient_list", "None"])
        else:
            # We want to use the list generated by the first run
            # The list is saved to "comparison_output" / args.output_dirs[0] / "selected_patients.txt"
            # Since generate_synthetic_patient_plots.py joins "comparison_output" with whatever is passed
            # we just need to pass: os.path.join(args.output_dirs[0], "selected_patients.txt")
            patient_list_rel = os.path.join(args.output_dirs[0], "selected_patients.txt")
            plots_cmd.extend(["--patient_list", patient_list_rel])
            
        result_plots = subprocess.run(plots_cmd)
        if result_plots.returncode != 0:
            print(f"Error: Patient plots script failed for {sample_file}.")
            sys.exit(result_plots.returncode)

    print(f"\n=== Synthetic Pipeline Completed Successfully ===")

if __name__ == "__main__":
    main()
